### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-server#111]
I heard this project is dead and is now being called mixer-tools and written in Go. Apparently it can't be used under Yocto which means projects using meta-swupd are stuck at the last released version. With swupd-server not being maintained anymore it kind of forces our project to look at an alternative.

**Comment by matthewrsj** [comment]
Yes! This particular project has been deprecated as of last week with the mixer v4.3.0 release (https://github.com/clearlinux/mixer-tools/releases/tag/v4.3.0). This mixer release made the new implementation the default and only implementation for swupd content generation going forward.

> Apparently it can't be used under Yocto which means projects using meta-swupd are stuck at the last released version.

That's unfortunate, but somewhat unexpected. The `mixer build update` command essentially implements the functionality provided by the `swupd-server` project. As I understand it there may be some additional work in mixer needed to download files on-demand. Is this what you are referring to?

Ideally you would be able to use `mixer build update` to create the same output that `swupd-server` generated.

> With swupd-server not being maintained anymore it kind of forces our project to look at an alternative.

This project is not being maintained any more. As of the mixer release last week it is deprecated. The mixer implementation however will be fully maintained going forward.

I will be updating the README this week to reflect the deprecation status of this project.

**Comment by aaronovz1** [comment]
@pohly seemed to suggest it won't be compatible with Yocto without a lot of work. See his comments here: https://github.com/pohly/meta-swupd/issues/6

**Comment by matthewrsj** [comment]
Ah, yes I now recall the issue with `pseudo`.

BTW, the architecture for mixer will be changing to run build commands in a docker container. The mixer build commands will no longer require the user to use `sudo` in this case. Maybe @pohly can comment if this new architecture fits his use case?

**Comment by pohly** [comment]
Running mixer under Docker instead of pseudo could work, albeit at the cost of introducing Docker as a new build dependency. I don't know whether users of the current meta-swupd would have a problem with that.

Just for your information, I am no longer working on meta-swupd. If someone is willing to continue with it, they are more than welcome to do so. But beware that it is not just the pseudo issue. Porting several of the PRs that I had pending for swupd server to mixer is also work that this future maintainer would need to do.

**Comment by matthewrsj** [comment]
Ok, but beyond the on-demand file download does anything else need to be ported? I believe the container architecture would allow you to no-longer need the libarchive changes, is that correct?

**Comment by pohly** [comment]
Matthew Johnson <notifications@github.com> writes:

> Ok, but beyond the on-demand file download does anything else need to
> be ported?

I think the alternative input layout (all in one file tree, bundles
defined by text files) is also currently missing in mixer. But you
wanted to add that, so perhaps it is there now. I haven't checked.

> I believe the container architecture would allow you to no-longer need
> the libarchive changes, is that correct?

Yes, that sounds plausible.

**Comment by matthewrsj** [comment]
> I think the alternative input layout (all in one file tree, bundles defined by text files) is also currently missing in mixer.

There have been some changes around mixer recently that may actually meet your needs. It is possible for you to provide a file list (via a JSON file) and a full file tree (we call the full chroot). The update command will then use this to create the actual manifests. I believe this covers your use case.

Happy to explain in more detail how that works if that sounds right to you.

**Comment by aaronovz1** [comment]
Is there already a docker container for mixer available? I'm not totally familiar with Docker but I assume once it's running on the host you can run commands inside the container? Does the container have access to files on the host and vice versa?

Looking at meta-swupd it looks like the main file that needs to be updated to use mixer is the invoke_swupd commands in swupd-image.bb? What are the equiv for swupd_create_update, swupd_make_pack, and swupd_make_fullfiles in mixer?

Lastly, at what point do you think swupd-client will become incompatible with the original swupd-server?

**Comment by matthewrsj** [comment]
> Is there already a docker container for mixer available?

Yes but the mixer feature to use the docker image under the hood is not merged yet. Here's the docker image that the build commands will be run inside: https://download.clearlinux.org/update/tools25/mixer.tar.xz

Mixer will run the commands you pass inside the container itself. You will not have to interact with the container, just mixer. The container will have access to a directory inside your mixer workspace.

> What are the equiv for swupd_create_update, swupd_make_pack, and swupd_make_fullfiles in mixer?

mixer build update, mixer build delta-packs

swupd_make_fullfiles is covered by mixer build update.

> Lastly, at what point do you think swupd-client will become incompatible with the original swupd-server?

I can't speculate on that. We don't have immediate plans to change manifest or content format, but we do have a couple long-term plans. Since these aren't scheduled I can't give you a timeframe.

**Comment by aaronovz1** [comment]
Probably my lack of understanding of Docker but if mixer requires inputs from Yocto sitting on the host, and the host requires the outputs from the mixer container, how does that work in this scenario?

**Comment by matthewrsj** [comment]
This initial commit message (WIP commit) explains some of it: https://github.com/kevincwells/mixer-tools/commit/8c0748f6729afba13a9ab1b03b58e13b8915f795 

Basically a shared directory is mounted in the container so it can write the files it needs to write. The input from the user (the command-line arguments) are passed to the mixer that is running in the container. The mixer in the container also has access to read whatever files it needs from the shared directory itself.

**Comment by aaronovz1** [comment]
Ok that makes more sense. So going off your previous comment, the docker container I'd need to start experimenting with this isn't ready just yet?

**Comment by matthewrsj** [comment]
Well, other way around actually. The docker container that mixer will download and use under the hood *is* ready, but the functionality for mixer to use that docker container has not yet been merged.

You *can* test these commands with the current mixer if you are able to use `sudo`. You can alternatively download that image I linked and run the mixer commands in that to see the output if you are just testing compatibility. To use the docker image under the hood and therefore not need sudo access on your build machine you will need to wait until the feature has been released.

**Comment by pohly** [comment]
Matthew Johnson <notifications@github.com> writes:

> Basically a shared directory is mounted in the container so it can
> write the files it needs to write. The input from the user (the
> command-line arguments) are passed to the mixer that is running in the
> container. The mixer in the container also has access to read whatever
> files it needs from the shared directory itself.

How are are file attributes handled in this scenario?

Suppose I run mixer as user "pohly". Does mixer inside the container run
as root, with the ability to create files as other users (root,
www-data, etc.)?

The input for mixer in meta-swupd consists of a .tar archive with all
files created in the current build. Currently it gets unpacked under
pseudo; in the future it would have to be unpacked inside the container.
Docker would then act like an elaborate "sudo".

The downside will be that deleting those files as normal user will not
work, should they get left behind by the container.

**Comment by matthewrsj** [comment]
@pohly correct mixer is running as root inside the container. 

> The downside will be that deleting those files as normal user will not work, should they get left behind by the container.

Interesting point. Calling @kevincwells, the engineer developing this feature, for more details. I'm not sure this case has been considered.

**Comment by matthewrsj** [comment]
I'll note that @kevincwells has spotty access to the internet right now, and may not respond until next week or so.

**Comment by icarus-sparry** [comment]
Yes, mixer is run as root inside the docker container, and so can write as anybody **inside** the container.

Docker manages its own "images", which is roughly a filesystem. https://docs.docker.com/storage/storagedriver Typically you have a number of overlays (layers), with the top one being writeable inside a container. When you exit a docker container instance then you have the option to "commit" the writeable overlay, which allows you to persist your changes. If you don't then they are garbage collected after some time. You can also explicitly remove containers which in practice means the writeable overlay, and remove images which means the unwriteable overlays.

You can mount files from the host into the docker image. Their permissions will depend if docker is invoked in trusted mode or not. If not then access will be as the user, i.e. this is closer to pseudo rather than sudo.

**Comment by pohly** [comment]
> Yes, mixer is run as root inside the docker container, and so can
> write as anybody **inside** the container.
...
> You can mount files from the host into the docker image. Their
> permissions will depend if docker is invoked in trusted mode or
> not. If not then access will be as the user, i.e. this is closer to
> pseudo rather than sudo.

So the million dollar question now is how these mechanisms of Docker
will be used by mixer, i.e. where it will write files with special
attributes (like uid 0).

If the unpacked rootfs is inside the container, everything is fine.

One other remark about "mixer chooses the Docker container based on the
format" (from the commit message): this implies that non-Clear Linux
developers will have to maintain their own Docker images for their
update stream, because format 10 in their update stream might use a
completely different tool version than the format 10 in Clear Linux.

Or will the Docker image selection be based on something other than the
current format number?

In meta-swupd, I had introduced a "tool format number" besides the
normal format number. The normal format number would get bumped when
either tools or distro content change in an incompatible way, while the
tool format number only got bumped when the tool changes such that the
update data becomes incompatible. Then during an update, meta-swupd
would automatically build the necessary tools based on the old and
potentially different new tool format and invoke the right tool as
needed (much like you now do via Docker images).

**Comment by aaronovz1** [comment]
Is @kevincwells still on spotty internet? I assume he will have the answers to Patricks questions.

**Comment by matthewrsj** [comment]
@kevincwells returned today and is still catching up on everything. He will get to this when he is able.

**Comment by kevincwells** [comment]
Hi folks. Back in the office now; sorry for the delay. I'll try to clear up some of the confusion.

> @aaronovz1 Is there already a docker container for mixer available?

There are a number of ways you can run mixer inside a container currently.
- The [clearlinux/clr-sdk](https://github.com/clearlinux/dockerfiles/tree/master/clr-sdk) Docker image (available on DockerHub) has all of the bundles needed to run mixer, as well as other dev tasks. It also has a lot of other bundles, though, so it's a bit large, and it has a default Entrypoint script (that runs whenever a container starts) that attempts to set up a non-root user linked to the workdir uid/gid.
- The [clearlinux/mixer-ci](https://github.com/clearlinux/dockerfiles/tree/master/mixer-ci) Docker Image (available on DockerHub) also has the mixer bundle pre-loaded. If you just want to "run mixer in a container" and not run other dev commands within the container, this might be a fast path to getting there.
- The base [clearlinux](https://hub.docker.com/_/clearlinux/) Docker Image (available on DockerHub) has just the very basic CLR OS installed, on which you could then `swupd bundle-add mixer`. This would be the slowest of the above options, but we're still only talking a few minutes of bundle install time. And you'd want to take a snapshot of your image after doing this (`docker commit`), or else you'd need to re-add mixer to the base image every time you run it. As @icarus-sparry pointed out, any changes you make within the running container (with the exception of changes within mounted directories) are erased once it exits.

The file @matthewrsj linked to ([mixer.tar.xz](https://download.clearlinux.org/update/tools25/mixer.tar.xz)) isn't actually a _Docker_ Image itself, it's the "OS content image" (overloaded word here) that mixer then uses to _build_ a "Docker Image" (`docker build`). This is definitely a more hands-on way of going about it, but if you want to see how we do it in the forthcoming feature, the Dockerfile we use is buried in the code in that commit @matthewrsj linked (https://github.com/kevincwells/mixer-tools/commit/8c0748f6729afba13a9ab1b03b58e13b8915f795). If you aren't familiar with Docker at all, I wouldn't recommend going this route.

> @aaronovz1 I'm not totally familiar with Docker but I assume once it's running on the host you can run commands inside the container?

Yes, the pages I linked above for the clr-sdk and mixer-ci images have instructions on how to run the containers in a way that lets you interact with it as if it were a terminal (i.e., passing `-i -t` to `docker run`). It's also possible to pass the specific command you want to run inside the container to the `docker run` command. You'd likely want the former (interactive terminal) if you're testing or trying things out, and the latter (run command in container and exit) if you're trying to script things.

> @aaronovz1 Does the container have access to files on the host and vice versa?

Yeah, as people have pointed out, you can bind-mount paths on the host to the container; this is typically how people "share" data between a host and a container. (It's also possible to copy data in and out of a running container, but that's more complicated.) You can mount multiple directories at the same time. The files within the mounted directory will have the same ownership and file attributes inside the container as they do on the host. That is, if there's a file in the mounted directory owned by UID 1010, it'll show up as owned by UID 1010 inside the container too. Just make sure you're running in the container as a user that has read/write permissions where it needs them. (By default you typically run as root in containers, so not an issue.)

The forthcoming mixer container functionality automatically mounts every valid directory listed in the mixer `builder.conf` file. If you're trying to test locally, you'd want to do the same. For a basic set up (e.g., if you're just following along with the mixer documentation tutorial), this is just the mixer working directory (where you're running mixer).

**Comment by kevincwells** [comment]
> @pohly How are are file attributes handled in this scenario?
> Suppose I run mixer as user "pohly". Does mixer inside the container run as root, with the ability to 
 reate files as other users (root, www-data, etc.)?
> The downside will be that deleting those files as normal user will not
work, should they get left behind by the container.

Yeah. As others have said, by default you run as root inside most containers (not just CLR ones), and that does mean that the files mixer creates inside the mounted directory are owned by uid 0. Up until now, `mixer build bundles` and `mixer build update` were being run with `sudo`, so this was already the case -- the content inside `$(SEVER_STATE_DIR)/www` is owned by root already. But if you are just testing and running an interactive container and running all mixer commands (`mixer init` and whatnot) inside the container, yeah, those will be owned by root now too.

Nothing forces you to run as root in a container, though. If you're just trying things out, you're definitely able to create a new user with whatever UID and GID you want inside the container, or `chown` anything you make.

For this very ownership reason, the above-linked [clearlinux/clr-sdk](https://github.com/clearlinux/dockerfiles/tree/master/clr-sdk) container uses an 'Entrypoint' scirpt to automatically create a new user inside the container that matches the workdir you mount

**Comment by kevincwells** [comment]
> @pohly So the million dollar question now is how these mechanisms of Docker will be used by mixer, i.e. where it will write files with special attributes (like uid 0).
> If the unpacked rootfs is inside the container, everything is fine.

The current working implementation of this "run mixer builds in a container automatically" feature does indeed run the build command as root inside the container, and so update content generated in the mounted directories is still owned by root. Again, this is no different than it has always been for users who were running `sudo mixer build update`. That said, there is an item on the backlist to chown the update content to match the ownership of the mounted directory. As this was actually a change from current behavior (where everything is owned by root), this was considered more of a nice-to-have improvement than a necessary feature.

**Comment by kevincwells** [comment]
> @pohly One other remark about "mixer chooses the Docker container based on the format" (from the commit message): this implies that non-Clear Linux developers will have to maintain their own Docker images for their update stream, because format 10 in their update stream might use a completely different tool version than the format 10 in Clear Linux.
> Or will the Docker image selection be based on something other than the
current format number?

That's a good observation. You're talking about a scenario in which someone creates a derivative of CLR using mixer (say, MyDistro), and then a user of MyDistro wants to run mixer in MyDistro to create a derivative of that derivative. Yes, in that case MyDistro would need to maintain a docker image stream as part of their release content. This is not the typical usage of mixer, however. Most mixer users are not expecting _their_ users to additionally be using mixer to create further derivatives, they're just trying to add their content on top of CLR.

To be a little more specific about how it works in the forthcoming feature, mixer uses the URL set in `upstreamurl` as the basis for where to pull the "OS Content Image" mentioned above, based on what format the _upstream version the mix is based on_ corresponds to. For example, if `upstreamurl` is set to `https://download.clearlinux.org/`, and a user is trying to build a mix based on CLR version 22310 (i.e., `upstreamversion` set to `22310`), mixer will look up that 22310 is in format 25 (e.g., by reading `https://download.clearlinux.org/update/22310/format`), and then do `"https://download.clearlinux.org/update/tools" + 25 + "/mixer.tar.xz"` to get the path of the file it downloads. So it's not the format number of the running system or something like that, it's the format number published in the release content of the upstream version the user is basing their mix on.

If a developer using mixer wants their users to also be able to run mixer in their derivative, those users would have `upstreamurl` set to, say, `https://mydistro.com`, and and so mixer would look at `https://mydistro.com/update/<VER>/format` and try to pull a file from, say, `https://mydistro.com/update/tools<DIFFERENT_FMT>/mixer.tar.xz`. So the developer making MyDistro would need all of those URLs to be valid.

Apologies if this explanation is confusing. I can go into more detail about what all a developer using mixer would need to do if they wanted their own users to also be able to user mixer in their derivative, if that's something people here need to know.

Lastly, this is, again, still an in-development feature, so internal guts of what mixer pulls from where could change slightly in the final released version.

**Comment by aaronovz1** [comment]
Thanks for the detailed responses @kevincwells. When I get some time I will setup the mixer-ci docker image and see how meta-swupd might integrate with it.

**Comment by aaronovz1** [comment]
Hi @matthewrsj @kevincwells,

I am starting to look at running the mixer-ci docker image as part of meta-swupd integration to replace the deprecated swupd-server. I hoping to get some pointers in how to use the docker image to do what I need.

I have mixer-ci running interactively using the following command:
`docker run -v /home/myuser/mix:/home/clr/mix -it clearlinux/mixer-ci`

Some questions to kick off some discussion:

1. What commands need to be run after the container is started? I see in the documentation mention of running `mixer init` but I don't see an option there that is applicable to using mixer the same way swupd-server was used in Yocto. ie: I don't need upstream to point to ClearLinux nor do I use local RPM's or git. Can I skip this command altogether?
2. In the previous swupd-server setup, the commands `swupd_create_update`, `swupd_make_fullfiles`, and `swupd_make_pack` were used and the `-S` for statedir was passed on the command line. I see in mix that the replacement for these commands are `mixer build update` and `mixer build delta-packs`. What I don't know is whether mix uses the same `statedir` structure as swupd-server. Does it still expect a `<statedir>/image` directory with LAST_VER file and folders for version numbers that have `<bundlename>-content.txt` and `full.tar` files inside them? Is the statedir mix equivalent the SERVER_STATE_DIR defined in the builder.conf?

Thanks

**Comment by kevincwells** [comment]
To get things started, for tracking purposes, it'd be best if you filed a new issue with your specific concerns. This closed issue will likely not get as much attention, and it's best to keep things focused on a single topic.

Second, I'll point out that the `clearlinux/mixer-ci` image might not be the right container to use for your purposes. It was built specifically to be run in Travis as part of mixer's continuous integration during development. As such, it might not have all of the packages you need for development -- it was designed for _building_ mixer, not _running_ it.

You could instead use the `clearlinux/clr-sdk` container. It's set up with all of the developer tools in the `os-clr-on-clr` bundle preloaded and configured for development. That said, it has gotten pretty large in the last year, and if you're not building your own RPMs, it might be overkill. We're working right now on a slimmer alternative for people who don't need dev packages, but that's not out yet.

For a lighter alternative, you could try running in the `clearlinux/mixer:<FORMAT>` image directly for the format you are building for - that's the mixer-only container that mixer itself uses behind the scenes to do builds.

Please note that for any of these, you will need to run mixer with the `--native` flag, so that mixer does not attempt to spawn a child container within the container itself.

@matthewrsj  will be able to help more with specific command-to-command port questions, but I strongly encourage you to read the [mixer documentation](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer) for a thorough rundown of what each command does, how to configure mixer, etc.
